image: gazben/php-ci:buster-apache-dev

stages:
  - install
  - test
  - build

variables:
  CONTAINER_TAG: ${CI_COMMIT_SHA}
  IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  IMAGE_TAG_DEV: ${CI_REGISTRY_IMAGE}:dev_latest
  IMAGE_TAG_RELEASE: ${CI_REGISTRY_IMAGE}:latest

cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - vendor/

###
# Install
###
install_composer:
  stage: install
  tags: [docker]
  before_script:
    - composer global require hirak/prestissimo --profile --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-interaction
  script:
    - composer install --no-dev --profile --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-interaction
  artifacts:
    expire_in: 30 mins
    paths:
      - vendor/

install_npm:
  image: node:12
  tags: [docker]
  stage: install
  script:
    - npm install
    - npm run production
  cache:
    paths:
      - public/
  artifacts:
    expire_in: 15 mins
    paths:
      - public/

###
# Test
###

inspect:
  stage: test
  tags: [docker]
  allow_failure: true
  cache:
    key: ${CI_COMMIT_SHA}
    policy: pull
  script:
    - touch test.sqlite
    - cp .env.testing .env
    - composer install --profile --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-interaction
    - php artisan key:generate
    - php artisan inspect

lint:
  stage: test
  tags: [docker]
  cache:
    key: ${CI_COMMIT_SHA}
    policy: pull
  script:
    - touch test.sqlite
    - cp .env.testing .env
    - composer install --profile --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-interaction
    - php artisan key:generate
    - php artisan lint

test:
  stage: test
  tags: [docker]
  cache:
    key: ${CI_COMMIT_SHA}
    policy: pull
  before_script:
    - composer config cache-files-dir /cache/composer
  script:
    - touch test.sqlite
    - cp .env.testing .env
    - composer install --profile --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-interaction
    - php artisan key:generate
    - php artisan test

###
# Build
###

.build_template:
  image: docker:latest
  cache:
    key: ${CI_COMMIT_SHA}
    policy: pull
  services:
    - docker:dind
  stage: build
  script:
    # version
    - echo -e "sha $CI_COMMIT_SHA\ntag ${CONTAINER_TAG}\nbuild_time $(date)" > version
    - cat version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}
    - docker tag ${IMAGE_TAG} ${IMAGE_TAG_DEV}
    - docker push ${IMAGE_TAG_DEV}

build_master:
  extends: .build_template
  tags: [docker]
  only:
    - master